apiVersion: apps/v1
kind: Deployment
metadata:
 name: myappdeployment
spec:
 replicas: 2
 template:
  metadata:
    name: myapppod
    labels:
     app: myapp
  spec:
   containers:
    - name: myapp-container
      image: stacksimplify/kubenginx:3.0.0
      ports:
       - containerPort: 80
 selector:
  matchLabels:
   app: myapp